spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-client
server:
  port: 7001
eureka:
  instance:
    hostname: localhost #服务器实例名称
  client:
    register-with-eureka: false #是否在eureka注册中心注册自己
    fetch-registry: false #为false表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
---
spring:
  profiles: test
  application:
    name: spring-cloud-config-client
server:
  port: 7002
eureka:
  instance:
    hostname: localhost #服务器实例名称
  client:
    register-with-eureka: false #是否在eureka注册中心注册自己
    fetch-registry: false #为false表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
